name: NovelTea CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout SFML
      uses: actions/checkout@v2
      with:
        repository: SFML/SFML
        path: SFML
    
    - name: Setup Linux Environment
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt install libxrandr-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev
        sudo apt install doxygen libgtest-dev
        
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2

    - name: Compile SFML
      run: |
        cd SFML
        mkdir install
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=../install -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE ..
        cmake --build . --config Release --target install
        cd ../..
        
    - name: Compile NovelTea
      run: |
        mkdir -p install/NovelTea
        mkdir -p doc/github.io/docs
        cmake -DBUILD_TEST=OFF -DCMAKE_INSTALL_PREFIX=./install/NovelTea -DSFML_DIR=./SFML/install/lib/cmake/SFML .
        cmake --build . --config Release --target install

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Test
      run: |
        echo hi
