name: NovelTea CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup Environment
      run: |
        sudo apt install libxrandr-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev
        sudo apt install doxygen libgtest-dev qt5-default
            
    - name: Compile SFML
      run: |
        git clone --depth 1 https://github.com/SFML/SFML.git
        cd SFML
        mkdir install
        mkdir build
        cd build
        cmake ../ -DBUILD_SHARED_LIBS=OFF
        make
        cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=../install -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE ..
        cmake --build . --config Release --target install
        cd ../..
        
    - name: Compile NovelTea
      run: |
        mkdir -p install/NovelTea
        mkdir -p doc/github.io/docs
        cmake $CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=./install/NovelTea -DSFML_DIR=./SFML/install/lib/cmake/SFML .
        cmake --build . --config Release --target install

  windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        
    - name: Compile SFML
      run: |
        git clone --depth 1 https://github.com/SFML/SFML.git
        cd SFML
        mkdir install
        mkdir build
        cd build
        cmake ../ -DBUILD_SHARED_LIBS=OFF
        make
        cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=../install -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE ..
        cmake --build . --config Release --target install
        cd ../..
